// frontend/components/RecipeCard.jsx
/**
 * RecipeCard.jsx
 * Personal Recipe Intelligence
 * レシピカードのレスポンシブ表示コンポーネント
 * - グリッド/リスト切り替え
 * - スワイプジェスチャー
 * - タッチ最適化
 */

import React, { useState, useRef, useEffect } from 'react';

/**
 * レシピカードコンポーネント
 * @param {Object} props - コンポーネントプロパティ
 * @param {Object} props.recipe - レシピデータ
 * @param {string} props.viewMode - 表示モード ('grid' | 'list')
 * @param {Function} props.onView - 閲覧ハンドラー
 * @param {Function} props.onEdit - 編集ハンドラー
 * @param {Function} props.onDelete - 削除ハンドラー
 */
const RecipeCard = ({
  recipe,
  viewMode = 'grid',
  onView,
  onEdit,
  onDelete,
}) => {
  const [isSwipeMenuOpen, setIsSwipeMenuOpen] = useState(false);
  const [touchStart, setTouchStart] = useState(null);
  const [touchEnd, setTouchEnd] = useState(null);
  const cardRef = useRef(null);

  // スワイプの最小距離（px）
  const minSwipeDistance = 50;

  // タッチ開始
  const handleTouchStart = (e) => {
    setTouchEnd(null);
    setTouchStart(e.targetTouches[0].clientX);
  };

  // タッチ移動
  const handleTouchMove = (e) => {
    setTouchEnd(e.targetTouches[0].clientX);
  };

  // タッチ終了
  const handleTouchEnd = () => {
    if (!touchStart || !touchEnd) return;

    const distance = touchStart - touchEnd;
    const isLeftSwipe = distance > minSwipeDistance;
    const isRightSwipe = distance < -minSwipeDistance;

    if (isLeftSwipe) {
      setIsSwipeMenuOpen(true);
    } else if (isRightSwipe) {
      setIsSwipeMenuOpen(false);
    }
  };

  // 外部クリックでメニューを閉じる
  useEffect(() => {
    const handleClickOutside = (e) => {
      if (cardRef.current && !cardRef.current.contains(e.target)) {
        setIsSwipeMenuOpen(false);
      }
    };

    if (isSwipeMenuOpen) {
      document.addEventListener('mousedown', handleClickOutside);
      document.addEventListener('touchstart', handleClickOutside);
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
      document.removeEventListener('touchstart', handleClickOutside);
    };
  }, [isSwipeMenuOpen]);

  // アクションハンドラー
  const handleAction = (action) => {
    setIsSwipeMenuOpen(false);
    if (action === 'view' && onView) {
      onView(recipe);
    } else if (action === 'edit' && onEdit) {
      onEdit(recipe);
    } else if (action === 'delete' && onDelete) {
      onDelete(recipe);
    }
  };

  // デフォルト画像URL
  const defaultImage = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="400" height="300"%3E%3Crect fill="%23f3f4f6" width="400" height="300"/%3E%3Ctext x="50%25" y="50%25" dominant-baseline="middle" text-anchor="middle" fill="%239ca3af" font-family="sans-serif" font-size="20"%3ENo Image%3C/text%3E%3C/svg%3E';

  return (
    <article
      ref={cardRef}
      className={`recipe-card ${viewMode} ${isSwipeMenuOpen ? 'menu-open' : ''}`}
      onTouchStart={handleTouchStart}
      onTouchMove={handleTouchMove}
      onTouchEnd={handleTouchEnd}
    >
      <div className="card-content">
        {/* 画像セクション */}
        <div className="card-image-wrapper">
          <img
            src={recipe.image || defaultImage}
            alt={recipe.title || 'レシピ画像'}
            className="card-image"
            loading="lazy"
          />
          {recipe.tags && recipe.tags.length > 0 && (
            <div className="card-tags">
              {recipe.tags.slice(0, 3).map((tag, index) => (
                <span key={index} className="card-tag">
                  {tag}
                </span>
              ))}
            </div>
          )}
        </div>

        {/* コンテンツセクション */}
        <div className="card-body">
          <h3 className="card-title">{recipe.title || '無題のレシピ'}</h3>

          {recipe.description && (
            <p className="card-description">{recipe.description}</p>
          )}

          <div className="card-meta">
            {recipe.cookTime && (
              <div className="meta-item">
                <svg
                  width="16"
                  height="16"
                  viewBox="0 0 16 16"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <circle cx="8" cy="8" r="7" stroke="currentColor" strokeWidth="1.5" />
                  <path d="M8 4V8L11 10" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                </svg>
                <span>{recipe.cookTime}分</span>
              </div>
            )}

            {recipe.servings && (
              <div className="meta-item">
                <svg
                  width="16"
                  height="16"
                  viewBox="0 0 16 16"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M8 8C9.65685 8 11 6.65685 11 5C11 3.34315 9.65685 2 8 2C6.34315 2 5 3.34315 5 5C5 6.65685 6.34315 8 8 8Z"
                    stroke="currentColor"
                    strokeWidth="1.5"
                  />
                  <path
                    d="M3 14C3 11.2386 5.23858 9 8 9C10.7614 9 13 11.2386 13 14"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                  />
                </svg>
                <span>{recipe.servings}人分</span>
              </div>
            )}

            {recipe.difficulty && (
              <div className="meta-item">
                <span className={`difficulty difficulty-${recipe.difficulty}`}>
                  {recipe.difficulty === 'easy' && '簡単'}
                  {recipe.difficulty === 'medium' && '普通'}
                  {recipe.difficulty === 'hard' && '難しい'}
                </span>
              </div>
            )}
          </div>

          {/* アクションボタン（デスクトップ） */}
          <div className="card-actions desktop-actions">
            <button
              onClick={() => handleAction('view')}
              className="btn btn-primary btn-sm"
              aria-label="レシピを見る"
            >
              見る
            </button>
            <button
              onClick={() => handleAction('edit')}
              className="btn btn-outline btn-sm"
              aria-label="レシピを編集"
            >
              編集
            </button>
            <button
              onClick={() => handleAction('delete')}
              className="btn btn-outline btn-sm btn-danger"
              aria-label="レシピを削除"
            >
              削除
            </button>
          </div>
        </div>
      </div>

      {/* スワイプメニュー（モバイル） */}
      <div className="swipe-menu">
        <button
          onClick={() => handleAction('edit')}
          className="swipe-action swipe-edit"
          aria-label="編集"
        >
          <svg
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M11 4H4C3.46957 4 2.96086 4.21071 2.58579 4.58579C2.21071 4.96086 2 5.46957 2 6V20C2 20.5304 2.21071 21.0391 2.58579 21.4142C2.96086 21.7893 3.46957 22 4 22H18C18.5304 22 19.0391 21.7893 19.4142 21.4142C19.7893 21.0391 20 20.5304 20 20V13"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
            <path
              d="M18.5 2.5C18.8978 2.10217 19.4374 1.87868 20 1.87868C20.5626 1.87868 21.1022 2.10217 21.5 2.5C21.8978 2.89782 22.1213 3.43739 22.1213 4C22.1213 4.56261 21.8978 5.10217 21.5 5.5L12 15L8 16L9 12L18.5 2.5Z"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
          <span>編集</span>
        </button>
        <button
          onClick={() => handleAction('delete')}
          className="swipe-action swipe-delete"
          aria-label="削除"
        >
          <svg
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M3 6H5H21"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
            <path
              d="M8 6V4C8 3.46957 8.21071 2.96086 8.58579 2.58579C8.96086 2.21071 9.46957 2 10 2H14C14.5304 2 15.0391 2.21071 15.4142 2.58579C15.7893 2.96086 16 3.46957 16 4V6M19 6V20C19 20.5304 18.7893 21.0391 18.4142 21.4142C18.0391 21.7893 17.5304 22 17 22H7C6.46957 22 5.96086 21.7893 5.58579 21.4142C5.21071 21.0391 5 20.5304 5 20V6H19Z"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
          <span>削除</span>
        </button>
      </div>

      <style jsx>{`
        /* ========================================
           Recipe Card Base
           ======================================== */
        .recipe-card {
          position: relative;
          display: flex;
          background-color: var(--color-background, #ffffff);
          border-radius: 0.75rem;
          overflow: hidden;
          box-shadow: var(--shadow-md, 0 4px 6px -1px rgba(0, 0, 0, 0.1));
          transition: all var(--transition-base, 0.25s ease-in-out);
        }

        .recipe-card:hover {
          box-shadow: var(--shadow-lg, 0 10px 15px -3px rgba(0, 0, 0, 0.1));
          transform: translateY(-2px);
        }

        .card-content {
          flex: 1;
          display: flex;
          transition: transform var(--transition-base, 0.25s ease-in-out);
        }

        .recipe-card.menu-open .card-content {
          transform: translateX(-160px);
        }

        /* ========================================
           Grid View
           ======================================== */
        .recipe-card.grid {
          flex-direction: column;
        }

        .recipe-card.grid .card-content {
          flex-direction: column;
        }

        .recipe-card.grid .card-image-wrapper {
          position: relative;
          width: 100%;
          padding-top: 75%;
          overflow: hidden;
        }

        .recipe-card.grid .card-image {
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          object-fit: cover;
        }

        /* ========================================
           List View
           ======================================== */
        .recipe-card.list {
          flex-direction: row;
        }

        .recipe-card.list .card-content {
          flex-direction: row;
        }

        .recipe-card.list .card-image-wrapper {
          position: relative;
          width: 120px;
          flex-shrink: 0;
          overflow: hidden;
        }

        .recipe-card.list .card-image {
          width: 100%;
          height: 100%;
          object-fit: cover;
        }

        .recipe-card.list .card-body {
          flex: 1;
        }

        /* ========================================
           Card Components
           ======================================== */
        .card-tags {
          position: absolute;
          top: 0.5rem;
          left: 0.5rem;
          display: flex;
          flex-wrap: wrap;
          gap: 0.25rem;
        }

        .card-tag {
          display: inline-block;
          padding: 0.25rem 0.5rem;
          background-color: rgba(255, 255, 255, 0.95);
          border-radius: 0.25rem;
          font-size: 0.75rem;
          font-weight: 500;
          color: var(--color-text, #1f2937);
          box-shadow: var(--shadow-sm, 0 1px 2px 0 rgba(0, 0, 0, 0.05));
        }

        .card-body {
          padding: 1rem;
          display: flex;
          flex-direction: column;
          gap: 0.5rem;
        }

        .card-title {
          margin: 0;
          font-size: 1.125rem;
          font-weight: 600;
          line-height: 1.4;
          color: var(--color-text, #1f2937);
          display: -webkit-box;
          -webkit-line-clamp: 2;
          -webkit-box-orient: vertical;
          overflow: hidden;
        }

        .card-description {
          margin: 0;
          font-size: 0.875rem;
          line-height: 1.5;
          color: var(--color-text-secondary, #6b7280);
          display: -webkit-box;
          -webkit-line-clamp: 2;
          -webkit-box-orient: vertical;
          overflow: hidden;
        }

        .card-meta {
          display: flex;
          flex-wrap: wrap;
          gap: 0.75rem;
          margin-top: auto;
        }

        .meta-item {
          display: flex;
          align-items: center;
          gap: 0.25rem;
          font-size: 0.875rem;
          color: var(--color-text-secondary, #6b7280);
        }

        .difficulty {
          padding: 0.125rem 0.5rem;
          border-radius: 0.25rem;
          font-size: 0.75rem;
          font-weight: 500;
        }

        .difficulty-easy {
          background-color: #d1fae5;
          color: #065f46;
        }

        .difficulty-medium {
          background-color: #fef3c7;
          color: #92400e;
        }

        .difficulty-hard {
          background-color: #fee2e2;
          color: #991b1b;
        }

        /* ========================================
           Actions
           ======================================== */
        .card-actions {
          display: flex;
          gap: 0.5rem;
          margin-top: 0.5rem;
        }

        .desktop-actions {
          display: none;
        }

        .btn {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          padding: 0.5rem 1rem;
          font-size: 0.875rem;
          font-weight: 500;
          border-radius: 0.375rem;
          border: none;
          cursor: pointer;
          transition: all var(--transition-fast, 0.15s ease-in-out);
        }

        .btn-sm {
          padding: 0.375rem 0.75rem;
          font-size: 0.8125rem;
        }

        .btn-primary {
          background-color: var(--color-primary, #4f46e5);
          color: white;
        }

        .btn-primary:hover {
          background-color: #4338ca;
        }

        .btn-outline {
          background-color: transparent;
          border: 1.5px solid var(--color-border, #e5e7eb);
          color: var(--color-text, #1f2937);
        }

        .btn-outline:hover {
          background-color: var(--color-surface, #f9fafb);
        }

        .btn-danger {
          color: var(--color-error, #ef4444);
          border-color: var(--color-error, #ef4444);
        }

        .btn-danger:hover {
          background-color: #fee2e2;
        }

        /* ========================================
           Swipe Menu
           ======================================== */
        .swipe-menu {
          position: absolute;
          top: 0;
          right: 0;
          bottom: 0;
          width: 160px;
          display: flex;
          transform: translateX(100%);
        }

        .swipe-action {
          flex: 1;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          gap: 0.25rem;
          border: none;
          color: white;
          font-size: 0.75rem;
          font-weight: 500;
          cursor: pointer;
          transition: opacity var(--transition-fast, 0.15s ease-in-out);
        }

        .swipe-action:active {
          opacity: 0.8;
        }

        .swipe-edit {
          background-color: var(--color-secondary, #06b6d4);
        }

        .swipe-delete {
          background-color: var(--color-error, #ef4444);
        }

        /* ========================================
           Responsive Styles
           ======================================== */
        @media (min-width: 768px) {
          .desktop-actions {
            display: flex;
          }

          .swipe-menu {
            display: none;
          }

          .recipe-card.list .card-image-wrapper {
            width: 200px;
          }

          .card-title {
            font-size: 1.25rem;
          }
        }

        @media (min-width: 1024px) {
          .recipe-card.list .card-image-wrapper {
            width: 240px;
          }
        }
      `}</style>
    </article>
  );
};

export default RecipeCard;

// frontend/src/components/RecipeCard.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import { getImageUrl } from '../services/api.js';

  export let recipe;
  export let viewMode = 'grid'; // 'grid' or 'list'

  const dispatch = createEventDispatcher();

  // State for image loading
  let imageLoaded = false;
  let imageError = false;

  // 画像ステータスに応じたプレースホルダー画像を生成
  function getPlaceholderImage() {
    const status = recipe.image_status;
    let text = 'No Image';
    let bgColor = '%23f0f0f0';
    let textColor = '%23999';

    if (status === 'API制限到達。後日再取得') {
      text = '画像取得待ち';
      bgColor = '%23fff3cd';  // 黄色系
      textColor = '%23856404';
    } else if (status === '画像ソースなし') {
      text = '画像なし';
      bgColor = '%23f8d7da';  // 赤系
      textColor = '%23721c24';
    }

    return `data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="200" height="150" viewBox="0 0 200 150"%3E%3Crect fill="${bgColor}" width="200" height="150"/%3E%3Ctext fill="${textColor}" font-family="sans-serif" font-size="12" x="50%25" y="50%25" dominant-baseline="middle" text-anchor="middle"%3E${encodeURIComponent(text)}%3C/text%3E%3C/svg%3E`;
  }

  // 画像URL取得
  function getRecipeImageUrl() {
    const imageUrl = getImageUrl(recipe);
    return imageUrl || getPlaceholderImage();
  }

  function handleImageLoad() {
    imageLoaded = true;
    imageError = false;
  }

  function handleImageError() {
    imageError = true;
    imageLoaded = true;
  }

  function formatTime(minutes) {
    if (!minutes) return null;
    if (minutes < 60) return `${minutes}分`;
    const hours = Math.floor(minutes / 60);
    const mins = minutes % 60;
    return mins > 0 ? `${hours}時間${mins}分` : `${hours}時間`;
  }

  function getTotalTime() {
    const prep = recipe.prep_time_minutes || 0;
    const cook = recipe.cook_time_minutes || 0;
    const total = prep + cook;
    return total > 0 ? formatTime(total) : null;
  }

  function getSourceIcon(type) {
    const icons = {
      'manual': '✍️',
      'web': '🌐',
      'ocr': '📷',
      'api': '🤖',
    };
    return icons[type] || '📄';
  }

  function handleView() {
    dispatch('view', recipe);
  }

  function handleEdit() {
    dispatch('edit', recipe);
  }

  function handleDelete() {
    dispatch('delete', { id: recipe.id, title: recipe.title });
  }

  function handleFavorite() {
    dispatch('favorite', recipe);
  }

  function handleExportMarkdown() {
    // Markdownエクスポート - 直接ダウンロードリンクを開く
    const exportUrl = `/api/v1/recipes/${recipe.id}/export/markdown`;
    window.open(exportUrl, '_blank');
  }
</script>

{#if viewMode === 'grid'}
  <article class="card card--grid">
    <div class="card-image" on:click={handleView} on:keypress={handleView} role="button" tabindex="0">
      {#if !imageLoaded}
        <div class="image-skeleton"></div>
      {/if}
      <img
        src={getRecipeImageUrl()}
        alt={recipe.title}
        loading="lazy"
        class:loaded={imageLoaded}
        on:load={handleImageLoad}
        on:error={handleImageError}
      />
      {#if recipe.is_favorite}
        <span class="favorite-badge">⭐</span>
      {/if}
      <span class="source-badge" title={recipe.source_type}>
        {getSourceIcon(recipe.source_type)}
      </span>
    </div>

    <div class="card-content">
      <h3 class="card-title" on:click={handleView} on:keypress={handleView} role="button" tabindex="0">
        {recipe.title}
      </h3>

      {#if recipe.description}
        <p class="card-description">{recipe.description}</p>
      {/if}

      <div class="card-meta">
        {#if recipe.servings}
          <span class="meta-item" title="人前">
            <span class="meta-icon">👥</span>
            {recipe.servings}人前
          </span>
        {/if}
        {#if getTotalTime()}
          <span class="meta-item" title="調理時間">
            <span class="meta-icon">⏱️</span>
            {getTotalTime()}
          </span>
        {/if}
        {#if recipe.ingredient_count}
          <span class="meta-item" title="材料数">
            <span class="meta-icon">🥗</span>
            {recipe.ingredient_count}品
          </span>
        {/if}
      </div>

      {#if recipe.rating}
        <div class="card-rating">
          {#each Array(5) as _, i}
            <span class="star" class:star--filled={i < Math.round(recipe.rating)}>★</span>
          {/each}
          <span class="rating-value">({recipe.rating.toFixed(1)})</span>
        </div>
      {/if}
    </div>

    <div class="card-actions">
      <button class="action-btn action-btn--view" on:click={handleView} title="詳細を見る">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="18" height="18">
          <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/>
          <circle cx="12" cy="12" r="3"/>
        </svg>
      </button>
      <button class="action-btn action-btn--edit" on:click={handleEdit} title="編集">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="18" height="18">
          <path d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7"/>
          <path d="M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z"/>
        </svg>
      </button>
      <button class="action-btn action-btn--export" on:click={handleExportMarkdown} title="MDでダウンロード">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="18" height="18">
          <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/>
          <polyline points="7 10 12 15 17 10"/>
          <line x1="12" y1="15" x2="12" y2="3"/>
        </svg>
      </button>
      <button class="action-btn action-btn--favorite" class:active={recipe.is_favorite} on:click={handleFavorite} title="お気に入り">
        <svg viewBox="0 0 24 24" fill={recipe.is_favorite ? "currentColor" : "none"} stroke="currentColor" stroke-width="2" width="18" height="18">
          <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"/>
        </svg>
      </button>
      <button class="action-btn action-btn--delete" on:click={handleDelete} title="削除">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="18" height="18">
          <polyline points="3 6 5 6 21 6"/>
          <path d="M19 6v14a2 2 0 01-2 2H7a2 2 0 01-2-2V6m3 0V4a2 2 0 012-2h4a2 2 0 012 2v2"/>
        </svg>
      </button>
    </div>
  </article>
{:else}
  <article class="card card--list">
    <div class="list-image" on:click={handleView} on:keypress={handleView} role="button" tabindex="0">
      {#if !imageLoaded}
        <div class="image-skeleton"></div>
      {/if}
      <img
        src={getRecipeImageUrl()}
        alt={recipe.title}
        loading="lazy"
        class:loaded={imageLoaded}
        on:load={handleImageLoad}
        on:error={handleImageError}
      />
    </div>

    <div class="list-content">
      <div class="list-header">
        <h3 class="card-title" on:click={handleView} on:keypress={handleView} role="button" tabindex="0">
          {recipe.title}
        </h3>
        <div class="list-badges">
          {#if recipe.is_favorite}
            <span class="badge badge--favorite">⭐</span>
          {/if}
          <span class="badge badge--source" title={recipe.source_type}>
            {getSourceIcon(recipe.source_type)} {recipe.source_type}
          </span>
        </div>
      </div>

      {#if recipe.description}
        <p class="card-description">{recipe.description}</p>
      {/if}

      <div class="list-footer">
        <div class="card-meta">
          {#if recipe.servings}
            <span class="meta-item">👥 {recipe.servings}人前</span>
          {/if}
          {#if getTotalTime()}
            <span class="meta-item">⏱️ {getTotalTime()}</span>
          {/if}
          {#if recipe.ingredient_count}
            <span class="meta-item">🥗 {recipe.ingredient_count}品</span>
          {/if}
        </div>

        <div class="card-actions">
          <button class="btn btn--primary" on:click={handleView}>詳細</button>
          <button class="btn btn--secondary" on:click={handleEdit}>編集</button>
          <button class="btn btn--export" on:click={handleExportMarkdown} title="MDでダウンロード">📥 MD</button>
          <button class="btn btn--danger" on:click={handleDelete}>削除</button>
        </div>
      </div>
    </div>
  </article>
{/if}

<style>
  /* Grid View */
  .card--grid {
    background: white;
    border-radius: 16px;
    overflow: hidden;
    box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);
    transition: transform 0.2s, box-shadow 0.2s;
    display: flex;
    flex-direction: column;
  }

  .card--grid:hover {
    transform: translateY(-4px);
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.12);
  }

  .card-image {
    position: relative;
    aspect-ratio: 16 / 10;
    overflow: hidden;
    cursor: pointer;
  }

  .card-image img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    transition: transform 0.3s, opacity 0.3s;
    opacity: 0;
  }

  .card-image img.loaded {
    opacity: 1;
  }

  .image-skeleton {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%);
    background-size: 200% 100%;
    animation: skeleton-loading 1.5s infinite;
  }

  @keyframes skeleton-loading {
    0% {
      background-position: 200% 0;
    }
    100% {
      background-position: -200% 0;
    }
  }

  .card--grid:hover .card-image img {
    transform: scale(1.05);
  }

  .favorite-badge {
    position: absolute;
    top: 0.75rem;
    left: 0.75rem;
    font-size: 1.25rem;
    filter: drop-shadow(0 2px 4px rgba(0,0,0,0.3));
  }

  .source-badge {
    position: absolute;
    top: 0.75rem;
    right: 0.75rem;
    background: rgba(255, 255, 255, 0.9);
    padding: 0.25rem 0.5rem;
    border-radius: 6px;
    font-size: 0.875rem;
  }

  .card-content {
    padding: 1rem;
    flex: 1;
    display: flex;
    flex-direction: column;
  }

  .card-title {
    margin: 0 0 0.5rem 0;
    font-size: 1rem;
    font-weight: 600;
    color: #1a1a2e;
    cursor: pointer;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
  }

  .card-title:hover {
    color: #667eea;
  }

  .card-description {
    margin: 0 0 0.75rem 0;
    font-size: 0.85rem;
    color: #666;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
  }

  .card-meta {
    display: flex;
    flex-wrap: wrap;
    gap: 0.75rem;
    margin-top: auto;
  }

  .meta-item {
    display: flex;
    align-items: center;
    gap: 0.25rem;
    font-size: 0.8rem;
    color: #888;
  }

  .meta-icon {
    font-size: 0.9rem;
  }

  .card-rating {
    display: flex;
    align-items: center;
    gap: 0.125rem;
    margin-top: 0.5rem;
  }

  .star {
    color: #ddd;
    font-size: 0.875rem;
  }

  .star--filled {
    color: #ffc107;
  }

  .rating-value {
    font-size: 0.75rem;
    color: #888;
    margin-left: 0.25rem;
  }

  .card-actions {
    display: flex;
    gap: 0.25rem;
    padding: 0.75rem 1rem;
    border-top: 1px solid #f0f0f0;
    background: #fafafa;
  }

  .action-btn {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 0.5rem;
    border: none;
    border-radius: 8px;
    background: transparent;
    color: #666;
    cursor: pointer;
    transition: all 0.2s;
  }

  .action-btn:hover {
    background: #f0f0f0;
  }

  .action-btn--view:hover { color: #667eea; }
  .action-btn--edit:hover { color: #28a745; }
  .action-btn--export:hover { color: #17a2b8; }
  .action-btn--favorite:hover, .action-btn--favorite.active { color: #ff6b6b; }
  .action-btn--delete:hover { color: #dc3545; }

  /* List View */
  .card--list {
    display: flex;
    background: white;
    border-radius: 12px;
    overflow: hidden;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
    transition: box-shadow 0.2s;
  }

  .card--list:hover {
    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.12);
  }

  .list-image {
    width: 160px;
    min-width: 160px;
    cursor: pointer;
  }

  .list-image {
    position: relative;
  }

  .list-image img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    transition: opacity 0.3s;
    opacity: 0;
  }

  .list-image img.loaded {
    opacity: 1;
  }

  .list-image .image-skeleton {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%);
    background-size: 200% 100%;
    animation: skeleton-loading 1.5s infinite;
  }

  .list-content {
    flex: 1;
    padding: 1rem;
    display: flex;
    flex-direction: column;
  }

  .list-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 1rem;
    margin-bottom: 0.5rem;
  }

  .list-badges {
    display: flex;
    gap: 0.5rem;
    flex-shrink: 0;
  }

  .badge {
    padding: 0.25rem 0.5rem;
    border-radius: 6px;
    font-size: 0.75rem;
  }

  .badge--favorite {
    background: #fff3cd;
  }

  .badge--source {
    background: #e3f2fd;
    color: #1976d2;
  }

  .list-footer {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-top: auto;
  }

  .card--list .card-actions {
    border-top: none;
    background: transparent;
    padding: 0;
  }

  .btn {
    padding: 0.5rem 1rem;
    border: 1px solid #ddd;
    border-radius: 6px;
    background: white;
    font-size: 0.85rem;
    cursor: pointer;
    transition: all 0.2s;
  }

  .btn--primary {
    background: #667eea;
    color: white;
    border-color: #667eea;
  }

  .btn--primary:hover {
    background: #5a6fd6;
  }

  .btn--secondary:hover {
    background: #f5f5f5;
  }

  .btn--danger {
    color: #dc3545;
    border-color: #dc3545;
  }

  .btn--danger:hover {
    background: #fff5f5;
  }

  /* Responsive */
  @media (max-width: 640px) {
    .list-image {
      width: 100px;
      min-width: 100px;
    }

    .list-footer {
      flex-direction: column;
      align-items: flex-start;
      gap: 0.75rem;
    }
  }
</style>
